시그널링 클라이언트 추가
the-boyj/WebRTC_Android pull request #8
Opened 2019-02-01 12:15 UTC by bhw1994

issue #3 
    add socketio dependency
    add internet permission for socketio
    add signaling client , signaling interface
    add signaling event log method

2019-02-03 02:21 UTC, laco-dev commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public PublishSubject<JSONObject> errorEventSubject = PublishSubject.create();
모든 작업을 Subject로 하는것은 좋지 않습니다.
콜드 옵저버블이 가능한 부분은 대체해도 좋을 듯 합니다.

2019-02-03 02:21 UTC, laco-dev commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            object.put("deviceToken", deviceToken);
Key값은 상수로 관리하는 게 좋습니다.

2019-02-03 02:21 UTC, laco-dev commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            isConnected=false;
이부분도 = 사이에 띄워주세요.........

2019-02-03 02:21 UTC, laco-dev commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
인터페이스에 상수면 final이 같이 적용 되던가요?
생각으 해봤는데 key값을 대문자로 관리하는것이 좋을 듯 합니다.

2019-02-03 03:24 UTC, jadenjack commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
- 상수 문자열이므로 static final 까지 붙이는게 더 낫다고 생각합니다.
- peer_error는 peerError로 수정해야 될 것 같습니다.
- 일단 대문자로 이벤트명을 바꾸는 것은 처음 얘기가 나온 것이기 때문에 다음 모임때 논의해봐야할 것 입니다.

2019-02-05 08:40 UTC, seokhyun-oh requested changes

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
이 형태는 url이 아닙니다.
url은 프로토콜, 호스트, 포트, path, 파라미터 등을 모두 포함합니다.

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    }
별도의 메소드에서 초기화 하는 이유가 있나요?

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public PublishSubject<JSONObject> errorEventSubject = PublishSubject.create();
이후 추가되는 모든 이벤트도 SignalingClient 클래스에서 처리할 계획인가요?

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +        }
예외 핸들링이 필요해보입니다.

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            object.put("deviceToken", deviceToken);
만약 deviceToken을 사용하지 않거나 추가적인 인자가 필요할 경우 메소드를 다시 작성해야 하는건가요?
별도의 serializable 객체를 만들어서 인자로 받는게 좋지 않을까요?

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public void emitAwaken(String room){
인자의 변화에 대하여 ```emitDial```과 같은 문제를 갖고있는거 같습니다.

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            isConnected=false;
connect, close 메소드의 접근 제어자를 public으로 한 이유가 있나요?

2019-02-05 08:40 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/utils/Logger.java
> +    public static void signalingEvent(String eventString) {Log.i("SignalingEvent", eventString);}
함수 바디를 한 줄로 표현하는 것은 피하는게 좋습니다.

2019-02-07 13:17 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public PublishSubject<JSONObject> errorEventSubject = PublishSubject.create();
네트워크 통신의 특성상 이벤트를 받았을때에만 의미가 있는 것이므로 , 옵저버가 구독 한 시점 이전의 데이터를 모두 전달해 주는 콜드 옵저버블은 문제가 된다고 생각합니다. 
모든 작업을 Subject로 하는것은 좋지 않은 이유가 무엇입니까?

2019-02-07 13:17 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public PublishSubject<JSONObject> errorEventSubject = PublishSubject.create();
SignalingClient 는 이벤트를 수신했음을 알려주는 역할만 합니다. 
이벤트 처리는 해당 서브젝트를 구독하는 클래스에서 합니다.

2019-02-07 13:17 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    }
소켓을 재활용 해야하는 상황을 고려하여 initSocket 이라는 메소드를 별도로 구현하였습니다.

2019-02-07 13:17 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +        }
빠른 기능 테스트를 하기 위해서 예외처리는 다음 이슈로 넘기겠습니다.
예외처리가 필요한 부분은 TODO 주석으로 마크 해놓았습니다.

2019-02-07 14:05 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    }
그렇다면 소켓이 닫혀있을 때 getInstance()를 통해 초기화 되지 않은 객체를 받을 수 있다는 의미인가요?

2019-02-07 14:10 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +        }
이슈 생성 후 resolve 부탁드립니다.

2019-02-07 14:18 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
다음과 같은 코드는 어떤가요?

```java
private static final String IP = "13.124.41.104";

...
final String url = String.format("http://%s:%d", IP, PORT);
socket = IO.socket(url);
```

2019-02-07 14:38 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +        }
issue #10

2019-02-07 14:39 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            isConnected=false;
수정하였습니다. 
Lint 를 적용할 필요가 있습니다.

2019-02-09 07:00 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            object.put("deviceToken", deviceToken);
이벤트 핸들링 부분은 다음 이슈로 넘겼습니다.

2019-02-09 07:01 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
수정하였습니다.

2019-02-09 07:02 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            object.put("deviceToken", deviceToken);
이벤트별 payload 클래스를 만들어 처리하겠습니다.
각 이벤트 핸들링은 다음 이슈로 넘깁니다.

2019-02-09 07:03 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public void emitAwaken(String room){
위와같습니다.

2019-02-09 07:03 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            isConnected=false;
private 로 수정하였습니다.

2019-02-09 07:09 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    }
생성자에서 초기화 하도록 하였습니다.

2019-02-09 07:19 UTC, jadenjack commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
[38f0fe](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/38f0feac6915fcf273f83a744b34411a077cc18f) 에 반영하였습니다.

2019-02-09 07:21 UTC, jadenjack commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
```
Code 첨부 예시
private static final String str = 'hello';
```

2019-02-09 07:30 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
://은 구분자입니다. 프로토콜이 아닙니다.

2019-02-09 07:40 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
인터페이스 에는 static , final 키워드가 필요 없습니다.

2019-02-09 07:40 UTC, shooes270 commented
[](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/30f151150207d1f3d0c44fdd0ef69fe7c76c65e1)

2019-02-09 07:43 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
peer_error -> peerError 수정 했습니다. [link](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/73cad41a4caec9e716b777312c86560100bdf533)

2019-02-09 07:44 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            isConnected=false;
close() 메소드는 삭제된건가요?

2019-02-09 07:45 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    private static final String URL = "http://13.124.41.104:";
:// 을 프로토콜 에서 뺏습니다. [link](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/6cb9f9c619139002cad8eb8ba6faf6834cc1bd42)

2019-02-09 07:47 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +            isConnected=false;
삭제된 메소드들은 테스트 케이스와 함께 다음 풀리퀘스트에 포함시키겠습니다.

2019-02-09 08:40 UTC, bhw1994 commented
> [30f151](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/30f151150207d1f3d0c44fdd0ef69fe7c76c65e1) payload 클래스들이 지워진걸로 확인됩니다.

이벤트 핸들링 메소드들을 구현하는 풀리퀘스트에 포함하는게 적합하다고 생각하여 뺐습니다.

2019-02-09 08:45 UTC, shooes270 commented
> > [30f151](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/30f151150207d1f3d0c44fdd0ef69fe7c76c65e1) payload 클래스들이 지워진걸로 확인됩니다.
> 
> 이벤트 핸들링 메소드들을 구현하는 풀리퀘스트에 포함하는게 적합하다고 생각하여 뺐습니다.

emitDial과 emitAwaken 메소드가 남아있는 것으로 봐서 지금 상태로 빌드가 실패할거같습니다.

2019-02-09 09:31 UTC, bhw1994 commented
> > > [30f151](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/30f151150207d1f3d0c44fdd0ef69fe7c76c65e1) payload 클래스들이 지워진걸로 확인됩니다.
> > 
> > 
> > 이벤트 핸들링 메소드들을 구현하는 풀리퀘스트에 포함하는게 적합하다고 생각하여 뺐습니다.
> 
> emitDial과 emitAwaken 메소드가 남아있는 것으로 봐서 지금 상태로 빌드가 실패할거같습니다.

해당 메소드들은 삭제되었습니다. 
issue#19  에서 추가 예정입니다. [link](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/30f151150207d1f3d0c44fdd0ef69fe7c76c65e1)

2019-02-09 09:38 UTC, seokhyun-oh approved these changes

2019-02-09 09:38 UTC, shooes270 commented
@bhw1994 
나머지 conversation들 다 resolve된 후에 머지 부탁합니다.

2019-02-09 10:15 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
@bhw1994 [해당 커밋](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/73cad41a4caec9e716b777312c86560100bdf533#diff-07e14fc24f0ec4d40a24ed0e9d9b35a9R4)에 public, static, final과 같은 키워드는 뭔가요?

2019-02-09 11:16 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
테스트 코드가 올라간듯 합니다 수정하였습니다. [link](https://github.com/the-boyj/WebRTC_Android/pull/8/commits/6477c246a690b75b04967121cf333f6c673dd3d8)

2019-02-12 04:49 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public PublishSubject<JSONObject> errorEventSubject = PublishSubject.create();
@tbtzpdlql @bhw1994 
Rx의 cold, hot observable 개념에 대해 찾아보았습니다. 

해당 subject들은 소켓객체 생성 직후 signaling server에 **연결 이전**에 생성되는 객체입니다.
따라서 **Cold Observable을 사용하여 연결 이전의 서버측 메시지를 수신 할 이유는 없어보입니다.**

PR이 너무 길어지고있으며 다른 conversation이 모두 resolve된 바 더이상의 의견이 없으면 해당 대화는 resolve하도록 하겠습니다.

2019-02-12 04:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingInterface.java
> +    String EVENT_PEER_ERROR = "peer_error";
@tbtzpdlql 
해당 이슈가 나왔을 때 스펙 기준으로 해당 코드가 맞습니다만 지적해주신 점 매우 공감하는 바입니다.
하지만 이는 시그널링 서버와의 공통된 이슈로서 단독으로 해결하기 힘들며, 이후 스펙을 재조정하여 새로운 이슈에서 해당 부분을 해결하는게 적절해 보입니다.

그 외의 상수와 관련된 질문에 대해서는 위의 댓글에서 충분한 설명이 된 것 같습니다.

따라서 해당 conversation은 resolve하도록 하겠습니다.

2019-02-12 04:55 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/signalling/SignalingClient.java
> +    public PublishSubject<JSONObject> errorEventSubject = PublishSubject.create();
오해의 여지가 있어 부가설명 하겠습니다.
시그널링 서버는 앱의 socketio-client 객체가 연결된 이후에 메시지를 emit할 수 있습니다.
따라서 cold observable로 만들더라도 수신할 메시지가 없음을 알려드립니다.

2019-02-16 15:16 UTC, laco-dev approved these changes

2019-02-16 15:22 UTC, merged