파이어베이스 서비스 추가
the-boyj/WebRTC_Android pull request #9
Opened 2019-02-01 12:16 UTC by bhw1994

issue #4 
      add FireStore. using FireStoreManager, access Firestore.
      add FCM. using MyFireBaseMessagingService , receive fcm message

    add UserDAO . using UserDAO, access User data from FireStore

    if you want to run client app, you need key at
    ~/app/google_services.json
    go to our google drive and download these files.

2019-02-03 02:38 UTC, tbtzpdlql commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-core:16.0.6'
각 라이브러리에 대해 주석으로 간단하게 구분 부탁드려요

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/DeviceTokenManager.java
> +            FirebaseInstanceId.getInstance().getInstanceId().addOnCompleteListener(task -> {
체인별로 개행해서 구분해주면 좋을 것 같습니다.

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/DeviceTokenManager.java
> +                emitter.onError(e);
이부분은 메소드 레퍼런스로 바로 사용이 가능합니다.

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +    public static CollectionReference getCollection(String collection){
외부에서 호출하는 메소드는 필수로 필요하다면 `@NonNull` 어노테이션 추가하는게 좋습니다.

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +    private static FirebaseFirestore db;
매니저가 수시로 생성되는 경우가 있나요?
db를 싱글톤으로 가지고 있는데 매니저는 그렇지 않아서
뭔가 애매합니다. `FireStoreManager.db.~~~` 로 사용하기보다는 레퍼런스를 가지고
내부에서 호출후 결과를 리턴받는것도 좋아 보입니다.

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/MyFirebaseMessagingService.java
> +        startActivity(intent);
`startActivity`는 EXTRA에 대해 안전하게 해당 액티비티에서 static으로 호출 한 결과를 받아서 처리하는게 좋습니다.

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
이 점도 같습니다. 메소드를 static으로 호출하는 경우는 레퍼런스가 필요 없을때 인 것 같습니다.
제 생각에는 가급적 레퍼런스를 갖고 호출하는것이 좋아보이는데
어떻게 생각하시나요

2019-02-03 02:38 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +        return DeviceTokenManager.getDeviceToken().flatMap(new Function<String, Single<String>>() {
람다식으로 하면 좀더 간결해 보일듯합니다.
`getDeviceToken`이 `Single`을 리턴하는데 이것을 flatMap으로 Single로 만든것으로 보입니다.
다른 쉬운 방법이 있지 않을까요?
현재 디바이스 토큰 관리를 어떻게 하는지 몰라서 정확히 전달을 못드려서 죄송합니다.

2019-02-05 08:54 UTC, seokhyun-oh requested changes

2019-02-05 08:54 UTC, shooes270 commented on app/src/androidTest/java/com/webrtc/boyj/api/firebase/FireStoreManagerTest.java
> +        assertEquals(UserDAO.COLLECTION_NAME, FireStoreManager.getCollection(UserDAO.COLLECTION_NAME).getId());
상수를 테스트 할 필요는 없어보입니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/androidTest/java/com/webrtc/boyj/api/firebase/FireStoreManagerTest.java
> +        CompletableFuture<String> future=new CompletableFuture<>();
테스트 명은 주로 should로 시작하여 테스트가 원하는 바를 구체적으로 명시해야 합니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/androidTest/java/com/webrtc/boyj/api/firebase/FireStoreManagerTest.java
> +        }
e.printStackTrace는 테스트 시 전혀 필요 없는 구문입니다.
성공을 확인하는 테스트에서 에러가 발생할 경우 그 테스트는 실패한 것으로 간주하는것이 옳습니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/androidTest/java/com/webrtc/boyj/api/firebase/FireStoreManagerTest.java
> +    }
해당 작업이 실패하는 것을 가정한 테스트는 없는건가요?

2019-02-05 08:54 UTC, shooes270 commented on app/src/androidTest/java/com/webrtc/boyj/api/firebase/FireStoreManagerTest.java
> +    }
이 테스트를 연속하여 실행할 경우 수행결과가 일정함이 보장되는건가요?

2019-02-05 08:54 UTC, shooes270 commented on app/src/androidTest/java/com/webrtc/boyj/model/dao/UserDAOTest.java
> +public class UserDAOTest {
```FireStoreManagerTest ```에 언급한 코멘트와 같으므로 생략하겠습니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/firebase/DeviceTokenManager.java
> +                emitter.onSuccess(token);
한번만 초기화 되는 변수의 경우 final을 사용할 경우 가독성이 더 좋아집니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +            task=db.collection(collection).document(documentId).set(data);
collection이 null이거나 Firebase상의 collection 문서가 없을 경우 어떻게 작동하는건가요?

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/firebase/MyFirebaseMessagingService.java
> +    // [END receive_message]
해당 주석은 의미없는 것으로 보입니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/UserRepository.java
> +        return UserDAO.readAll();
데이터에 대한 cache로서 사용되지 않는다면 UserRepository 클래스의 존재 의의가 퇴색되는것으로 알고있습니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +                }
해당 에러가 이후 어떻게 처리되는건지 설명 부탁드립니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +                data.put(KEY_TEL, "010-0000-0000");
s와 data 변수에 좀 더 적절한 변수명 혹은 주석이 필요해보입니다.

2019-02-05 08:54 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +
사용하지 않는 코드는 제거하는게 좋습니다.

2019-02-06 07:19 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +    private static FirebaseFirestore db;
@tbtzpdlql 
정적메소드만 지원하는걸 봐서는 인스턴스가 생성될거같지 않습니다.

2019-02-07 13:18 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +    private static FirebaseFirestore db;
매니저는 스태틱메소드만 가지고 있는 클래스이므로, 매니저의 인스턴스 생성되지 않습니다.
FireStore Instance를 싱글톤으로 관리하는것은 FireBase API 입니다.
위에서 말한것 처럼 , 매니저의 인스턴스는 생성되지 않고 , FireStore 인스턴스를 스태틱변수에 저장하므로 문제가 없어 보입니다.
 FireStoreManager.db ~~ 이런식으로 호출 하는 경우는 없습니다. 모든경우 FireStoreManager 의 스태틱 메소드로 접근합니다.

2019-02-07 13:18 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
레퍼런스를 갖고 호출해야하는 이유가 있나요?
해당 클래스는 멤버변수를 가지고 있지 않고 데이터베이스에 접근하는 클래스이므로 static 메소드가 더 어울려 보입니다.

2019-02-07 13:19 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/firebase/MyFirebaseMessagingService.java
> +        startActivity(intent);
CallAtcitiy.goToCallActivity 구현 하였습니다. [link](https://github.com/the-boyj/WebRTC_Android/pull/9/commits/0a09e9a4eea62d3dd79c2b8b9ce5e5488be50818)

2019-02-07 14:00 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
@bhw1994 
지적하신 바와 같이 프로퍼티가 없는 클래스이므로 static method를 써도 기능상의 문제는 없습니다.
다만 OOP의 관점에서 보았을 때, static method는 객체지향의 메서드보단 c언어 스타일의 함수라고 보는 것이 적절하다는 뜻으로 @tbtzpdlql 께서 언급한 것 같습니다.

첨언하자면 static method는 주로 유틸리티를 위한 함수에 사용되는 것으로 알고 있습니다.

2019-02-07 14:40 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/firebase/DeviceTokenManager.java
> +            FirebaseInstanceId.getInstance().getInstanceId().addOnCompleteListener(task -> {
수정하였습니다.

2019-02-07 14:43 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
데이터베이스 매니저 클래스는 일반적으로 싱글톤이나 스태틱으로 사용하는것으로 알고 있는데
더 좋은 방법이나 의견 있으시면 남겨주세요
@shooes270  @tbtzpdlql  @jadenjack

2019-02-07 14:45 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +        return DeviceTokenManager.getDeviceToken().flatMap(new Function<String, Single<String>>() {
디바이스 토큰을 가져오는 작업은 비동기 작업입니다.
디바이스 토큰을 얻은후에 다음 작업을 해야 하므로 또다른 Single을 만들어 리턴하였습니다.
좋은 방법이 있다면 남겨주세요
@tbtzpdlql

2019-02-07 14:48 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/UserRepository.java
> +        return UserDAO.readAll();
기존의 계획한 설계대로 구현하였습니다.
하지만 저도 이부분에 대해선 현재 목표와 비교하여 오버엔지니어링이라 생각이 듭니다.
의견주세요
@tbtzpdlql

2019-02-07 15:09 UTC, seokhyun-oh commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
@bhw1994 
안드로이드에서의 경험이 없는지라 백엔드 관점에서 아는대로 서술하겠습니다.

DAO(Data Access Object)에 앞서 DataSource라는 이름의 커넥션 객체 혹은 스레드풀 운영하여 데이터베이스 혹은 파일시스템과의 커넥션을 유지합니다. 이 때, 이 DataSource를 static variable로 운영하지만 Singleton으로 운영하는것은 못본거같습니다.

이후 인스턴스화된 DAO에서 추상화된 DataSource에 질의를 보내고 상위 계층에서 이해할 수 있게 객체로 매핑합니다. 이 상황에서 DAO는 주로 stateless지만 앞서 설명한 이유로 static method가 아닌 인스턴스의 메소드로 기능을 제공합니다. 물론 최적화 관점에서 인스턴스 생성을 최소화 하기 위해 별도의 싱글톤 레지스트리에 담는 방식도 존재합니다. (대표적으로 SpringMVC)

정리하면 다음과 같습니다.
DataSource: IO와 관련된 생성, 관리, 소멸, 예외 핸들링에 대한 책임을 갖는 클래스.
XXXDao: DataSource에 질의를 던져 값을 가져오고 상위 계층에서 이해할 수 있는 형태로 변환하는 책임을 갖는 클래스.

여기까지가 백엔드 관점에서 본 DAO와 DataSource의 의미였습니다. 본 Pull Request에 대입하여 생각한다면 DataSource는 FireStoreManager가 그 역할을 한다고 생각합니다. 이는 FirebaseFirestore 인스턴스를 static variable로서 관리하는것을 토대로 추측한 것입니다.

2019-02-07 15:19 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
추가적으로 SpringMVC에서는 DataSource를 싱글톤 레지스트리에 저장하여 사용하지만, 이는 보편적으로 알려진 싱글톤 패턴과는 상당한 차이를 갖습니다. 오히려 static variable로 사용하는것과 같다고 보는것이 맞을거 같습니다.

2019-02-08 07:15 UTC, bhw1994 commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-core:16.0.6'
추가 하였습니다.

2019-02-08 07:26 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/firebase/DeviceTokenManager.java
> +                emitter.onError(e);
수정하였습니다

2019-02-08 07:43 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +    public static CollectionReference getCollection(String collection){
Issue #1 에서 일괄 처리하는게 좋아 보입니다.

2019-02-08 08:02 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +                }
issue #10 에서 처리 하겠습니다.

2019-02-08 13:32 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +            task=db.collection(collection).document(documentId).set(data);
리스너 패턴으로 성공 실패에 대한 처리를 할 수 있습니다.

2019-02-08 13:34 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/model/UserRepository.java
> +        return UserDAO.readAll();
레포지 터리에서 파이어베이스 접근 할 수 있는 레퍼런스를 가지고 있는것으로 생각했습니다. 위에서 제시하신 대로 한다면 뷰모델이 userdao를 가지고 있어야 하는데 관계가 좀 모호한것 같습니다.

2019-02-09 07:04 UTC, shooes270 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +        return DeviceTokenManager.getDeviceToken().flatMap(new Function<String, Single<String>>() {
@bhw1994 여담입니다만 rxjava의 [Completable](http://reactivex.io/RxJava/javadoc/io/reactivex/Completable.html)를 사용하면 [andThen()](http://reactivex.io/RxJava/javadoc/io/reactivex/Completable.html#andThen-io.reactivex.CompletableSource-)을 이용하여 비동기 작업간의 순서 보장 할 수 있는걸로 알고있습니다.

2019-02-09 09:48 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
인스턴스화 하여 사용하게끔 static 키워드를 제거하였습니다.[link](https://github.com/the-boyj/WebRTC_Android/pull/9/commits/b86a9bc471ffd698b694d103dfa79c20a94f9cdc)

2019-02-09 13:31 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +        return DeviceTokenManager.getDeviceToken().flatMap(new Function<String, Single<String>>() {
디바이스 토큰을 create 내부에서 하지 않게 되었으므로 밑의 코드처럼 간단하게 바꾸었습니다.
```
public Single<String> create(User user){
        return FireStoreManager.createDocument(COLLECTION_NAME ,user ,FireStoreManager.AUTO_CREATE_DOCUMENT_ID);
    }
```
[7ba7e7e0](https://github.com/the-boyj/WebRTC_Android/pull/9/commits/7ba7e7e06162bcf9ecfdebca7aacffd613583d6d)

2019-02-09 13:41 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +                data.put(KEY_TEL, "010-0000-0000");
외부에서 유저 객체를 받아오는것으로 수정하여서 이부분은 삭제 되었습니다.
[link](https://github.com/the-boyj/WebRTC_Android/pull/9/commits/7ba7e7e06162bcf9ecfdebca7aacffd613583d6d)

2019-02-10 05:12 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +    public static Single<String> create(String name){
issue #20  에서 로컬 , 리모트 레포지토리 패턴으로 구현이 필요하겠습니다.

2019-02-10 05:13 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/dao/UserDAO.java
> +        return DeviceTokenManager.getDeviceToken().flatMap(new Function<String, Single<String>>() {
issue #20  에서 로컬 , 리모트 레포지토리 로 구현이 필요하겠습니다.

2019-02-10 05:14 UTC, bhw1994 commented on app/src/main/java/com/webrtc/boyj/model/UserRepository.java
> +        return UserDAO.readAll();
issue #20  에서 로컬 , 리모트 레포지토리 로 구현이 필요하겠습니다.

2019-02-12 10:12 UTC, tbtzpdlql commented on app/src/main/java/com/webrtc/boyj/api/firebase/FireStoreManager.java
> +    private static FirebaseFirestore db;
네 이점은 이후 수정하게 된다면 다시 고민해보겠습니다.

2019-02-16 15:10 UTC, seokhyun-oh approved these changes

2019-02-16 15:23 UTC, merged